### ISSUE TITLE
Document what a lock is

### ISSUE THREAD

**Issue by jakobrosenberg** [avajs/cooperate#4]
This is all the documentation I could find on locks:

> **Locks**
> You can create a lock within a context:

https://github.com/avajs/cooperate

> **Available plugins**
> @ava/get-port works like get-port, but ensures the port is locked across all test files.
> @ava/cooperate implements locking and value reservation functionality.

https://github.com/avajs/ava/blob/master/docs/recipes/shared-workers.md

I'm not sure what it does or what I need it for.

**Comment by novemberborn** [comment]
> I'm not sure what it does or what I need it for.

You might not! Which is fine.

This is quite a low-level library, I think folks may only know to use it when they know to use it.

Would linking to the Wikipedia article on locks help? https://en.wikipedia.org/wiki/Lock_(computer_science)

**Comment by jakobrosenberg** [comment]
Thanks @novemberborn! That's not at all what I thought it was 😂
